from enum import Enum


class Form(Enum):
    LOGIN = "LOGIN"
    MAIN = "MAIN"
    SUBSCRIPTION = "SUBSCRIPTION"
    PICK_CLASS = "PICK_CLASS"
    ALL_CLASS = "ALL_CLASS"
    CLASS_TODAY = "CLASS_TODAY"
    POST_PLAN = "POST_PLAN"
    CLASS_BUNDLE = "CLASS_BUNDLE"
    TRAINER = "TRAINER"
    CLASS_MENU = "CLASS_MENU"
    BOOK_CLASS = "BOOK_CLASS"
